### ISSUE TITLE
Your MX is rejecting messages

### ISSUE THREAD

**Issue by savchenko** [komachi/icsend#8]
Would gladly contact you elsewhere, but as e-mail is unavailable...

```
<anton@nesterov.cc>: host mail.nesterov.cc[2a0a:c801:1:1::48] said: 550 5.7.23
    <anton@nesterov.cc>: Recipient address rejected: Message rejected due to:
    SPF fail - not authorized.
```

...please feel free to ping me at andrew@savchenko.net

Cheers.

**Comment by komachi** [comment]
Seems like to support ipv6 in docker you need [an additional hack](https://github.com/tomav/docker-mailserver/wiki/IPv6), so [my mailserver setup](https://github.com/komachi/ansible-docker-mailserver) failed to correctly validate mail if it got it via ipv6. Fixed in latest commit, so you can try again.

**Comment by savchenko** [comment]
Doesn't work just yet:
```
Reporting-MTA: dns; mout-p-101.mailbox.org
X-Postfix-Queue-ID: 4CZqV536kdzQkKN
X-Postfix-Sender: rfc822; andrew@savchenko.net
Arrival-Date: Tue, 17 Nov 2020 02:22:53 +0000 (UTC)

Final-Recipient: rfc822; komachi@openmailbox.org
Original-Recipient: rfc822;komachi@openmailbox.org
Action: failed
Status: 4.4.1
Diagnostic-Code: X-Postfix; connect to mail.openmailbox.org[195.154.27.123]:25:
    Connection refused
```
